server:
  port: ${APP_PORT:8080}
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /carshop
    application-display-name: CarShop
  tomcat:
    max-connections: 1000
    accept-count: 100
    connection-timeout: 30000

spring:
  application:
    name: my-app
  datasource:
    url: jdbc:postgresql://localhost:5432/carshop
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  jackson:
    default-property-inclusion: non_null


logging:
  level:
    ROOT: INFO
    ru.iteco: DEBUG
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  metrics:
    export:
      atlas:
        enabled: true

systemName:
  CarShop
organization:
  name:
    AntonCars
corePoolSize:
  4
maxPoolSize:
  12